"$schema" = "https://railway.app/railway.schema.json"

[build]
builder = "nixpacks"
command = "npm run install-all && npm run build:server"

[deploy]
startCommand = "npm run start:server"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "server"
root = "./server"
